accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.account_list, name='account_list'),
    path('create/', views.account_create, name='account_create'),
    path('<int:pk>/edit', views.account_edit, name='account_edit'),
    path('<int:pk>/delete', views.account_delete, name='account_delete'),

]

bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('book-appointment', views.appointment_set, name='appointment_set'),
    path('appointment/', views.appointment_list, name='appointment_list'),

]

splendor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', auth_views.LoginView.as_view(template_name='accounts/auth_login.html',
                                                authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('services/', include('services.urls')),
    path('accounts/', include('accounts.urls')),
    path('bookings/', include('bookings.urls'))

]

bookings/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from services.models import Treatment


# Create your models here.
class Appointment(models.Model):
    day = models.DateField(null=True, blank=True)
    TIME_CHOICES = [
        ("------", "------"),
        ("10 AM", "10 AM"),
        ("11 AM", "11 AM"),
        ("12 PM", "12 PM"),
        ("1 PM", "1 PM"),
        ("2 PM", "2 PM"),
        ("3 PM", "3 PM"),
        ("4 PM", "4 PM"),
        ("5 PM", "5 PM"),
        ("6 PM", "6 PM"),
        ("7 PM", "7 PM"),
        ("8 PM", "8 PM"),
        ("9 PM", "9 PM"),
    ]
    time = models.CharField(max_length=10, choices=TIME_CHOICES)
    treatment = models.ForeignKey(Treatment, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.day} {self.time}"

    class Meta:
        db_table = 'appointments'

bookings/forms.py
from django import forms
from django.forms import ModelForm, NumberInput

from services.models import Treatment
from .models import Appointment


class BookingForm(forms.ModelForm):

    day = forms.DateField(
        widget=NumberInput(
            attrs={'type': 'date',
                   'class': 'form-control'},
        )
    )

    time = forms.ChoiceField(
        choices=Appointment.TIME_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    treatment = forms.ModelChoiceField(
        queryset=Treatment.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control'}))

    class Meta:
        model = Appointment
        fields = [
            'day',
            'time',
            'treatment',
        ]

bookings/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import BookingForm
from .models import Appointment
from .models import Treatment


# Create your views here.
def appointment_set(request):
    form = BookingForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('bookings:appointment_list')

    context = {'form': form}
    return render(request, 'bookings/appointment_set.html', context)


def appointment_list(request):
    appointment_list = Appointment.objects.all()
    template_name = 'bookings/appointment_list.html'
    context = {'appointment_list': appointment_list}
    return render(request, template_name, context)

bookings/templates/bookings/appointment_list.html
{% extends 'base.html' %}

{% block title %}
    Appointment
{% endblock %}

{% block content %}

	<h5><a href="{% url 'bookings:appointment_set' %}">Set Appointment</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>Day</th>
					<th>Time</th>
					<th>Treatment</th>
				</tr>
			</thead>

			<tbody>
				{% for appointment in appointment_list %}
					<tr>
						<td>{{ appointment.day }}</td>
						<td>{{ appointment.time }}</td>
						<td>{{ appointment.treatment }}</td>
						<td><a href="#" class="btn btn-md btn-info">
							Edit</a>
							<a href="#" class="btn btn-md btn-danger">
							Delete</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}

bookings/templates/bookings/appointment_set.html
{% extends 'base.html' %}

{% block title %}
    Pricing Type
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
			<label>Day:</label>
			{{form.day}}
            {{form.day.errors}}
		</div>

        <div class="form-group">
			<label>Time:</label>
			{{form.time}}
            {{form.time.errors}}
		</div>

          <div class="form-group">
			<label>Treatment:</label>
			{{form.treatment}}
            {{form.treatment.errors}}
		</div>

        <button type="submit" class="btn btn-md btn-success">Add</button>
    </form>

{% endblock %}

bookings/templates/bookings/set_appointment.html
{% extends 'base.html' %}

{% block title %}
    Pricing Type
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
			<label>Day:</label>
			{{form.day}}
            {{form.day.errors}}
		</div>

        <div class="form-group">
			<label>Time:</label>
			{{form.time}}
            {{form.time.errors}}
		</div>

          <div class="form-group">
			<label>Treatment:</label>
			{{form.treatment.id}}
            {{form.treatment.errors}}
		</div>

        <button type="submit" class="btn btn-md btn-success">Add</button>
    </form>

{% endblock %}