accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.account_list, name='account_list'),
    path('create/', views.account_create, name='account_create'),
    path('<int:pk>/edit', views.account_edit, name='account_edit'),
    path('<int:pk>/delete', views.account_delete, name='account_delete'),

]

splendor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', auth_views.LoginView.as_view(template_name='accounts/auth_login.html',
                                                authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('services/', include('services.urls')),
    path('accounts/', include('accounts.urls')),
    path('bookings/', include('bookings.urls'))

]

accounts/models.py
from django.contrib.auth.hashers import make_password
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from datetime import date


# Create your models here.


class CustomUser(AbstractUser):
    username = models.CharField(max_length=11, unique=True, null=False, blank=False)
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=1000, null=False, blank=False)
    middle_name = models.CharField(max_length=100, null=False, blank=False)
    GENDER_CHOICES = [
        ('', '---------'),
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
    ]
    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
    )
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=255, unique=True, null=False, blank=False)
    ROLE_CHOICES = [
        ('', '---------'),
        ('PATIENT', 'Patient'),
        ('THERAPIST', 'Therapist'),
        ('ADMIN', 'Admin'),
    ]
    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
    )

    date_joined = models.DateTimeField(default=timezone.now)
    deleted_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, default='Available')

    USERNAME_FIELD = 'username'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        db_table = 'accounts'

accounts/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import NumberInput
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm


class RegistrationForm(forms.ModelForm):
    role = forms.ChoiceField(
        choices=CustomUser.ROLE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Firstname must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Lastname must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    middle_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Middle name must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    gender = forms.ChoiceField(
        choices=CustomUser.GENDER_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'})
    )

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^09\d{9}$',
                message='Invalid phone number format'),
        ],
        error_messages={
            'required': ''
        }
    )

    birth_date = forms.DateField(
        widget=NumberInput(
            attrs={'type': 'date',
                   'class': 'form-control'},
        )
    )

    class Meta:
        model = CustomUser
        fields = [
            'role',
            'first_name',
            'last_name',
            'middle_name',
            'gender',
            'email',
            'username',
            'birth_date',
        ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(  # This is always 'username'
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'email',
                'placeholder': 'Email'}
        )
    )
    password = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'name': 'password',
                'placeholder': 'Password'}
        )
    )

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import CustomUser
from .forms import RegistrationForm
from django.contrib import messages


# Create your views here.
def account_list(request):
    users = CustomUser.objects.exclude(status='Deleted')
    template_name = 'accounts/account_list.html'
    context = {'users': users}
    return render(request, template_name, context)


def account_create(request):
    form = RegistrationForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Account updated successfully.')
        return redirect('accounts:account_list')
    template_name = 'accounts/account_create.html'
    context = {'form': form}
    return render(request, template_name, context)


def account_edit(request, pk):
    users = get_object_or_404(CustomUser, id=pk)
    form = RegistrationForm(request.POST or None, instance=users)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'User account updated successfully.')
        return redirect('accounts:account_list')

    template_name = 'accounts/account_edit.html'
    context = {'users': users, 'form': form}
    return render(request, template_name, context)


def account_delete(request, pk):
    users = get_object_or_404(CustomUser, id=pk)
    users.status = 'Deleted'
    users.save()
    messages.success(request,
                     'User account has been deleted')
    return redirect('accounts:account_list')

accounts/templates/accounts/account_create.html
{% extends 'base.html' %}

{% block title %}
    Accounts
{% endblock %}

{% block content %}
<h1>Accounts</h1>
    <form method="POST" action="">
        {% csrf_token%}

		 <div class="form-group">
			<label>Role:</label>
			{{form.role}}
		</div>

        <div class="form-group">
			<label>First Name:</label>
			{{form.first_name}}
			{{form.first_name.errors}}

		</div>

        <div class="form-group">
			<label>Last Name:</label>
			{{form.last_name}}
			{{form.last_name.errors}}
		</div>

		<div class="form-group">
			<label>Middle Name:</label>
			{{form.middle_name}}
			{{form.middle_name.errors}}
		</div>

		 <div class="form-group">
			<label>Gender:</label>
			{{form.gender}}
		</div>

        <div class="form-group">
			<label>Email:</label>
			{{form.email}}
		</div>

        <div class="form-group">
			<label>Mobile:</label>
			{{form.username}}
			{{form.username.errors}}
		</div>

		<div class="form-group">
		    <label>Birthdate</label>
		   {{form.birth_date}}
		</div>

        <button type="submit" class="btn btn-md btn-success">Add</button>
    </form>

{% endblock %}

accounts/templates/accounts/account_list.html
{% extends 'base.html' %}

{% block title %}
    Accounts
{% endblock %}

{% block content %}
    <h5><a href="{% url 'accounts:account_create' %}">Add User</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Role</th>
					<th>First Name</th>
                    <th>Last Name</th>
                    <th>Middle Name</th>
                    <th>Birthdate</th>
                    <th>Email</th>
				</tr>
			</thead>

			<tbody>
				{% for user in users %}
					<tr>
						<td>{{ user.id }}</td>
						<td>{{ user.role }}</td>
						<td>{{ user.first_name }}</td>
						<td>{{ user.last_name }}</td>
						<td>{{ user.middle_name }}</td>
						<td>{{ user.birth_date }}</td>
						<td>{{ user.email}}</td>
						<td><a href="{% url 'accounts:account_edit' user.id %}" class="btn btn-md btn-info">
							Edit</a>
							<a href="{% url 'accounts:account_delete' user.id %}" class="btn btn-md btn-danger">
							Delete</a>
						</td>

					</tr>
				{% endfor %}

			</tbody>
		</table>
	</div>

{% endblock %}

accounts/templates/accounts/auth_login.html
{% extends "base_login.html" %}

{% block page_message %} Please log in to access this page {% endblock page_message %}

{% block content %}

{% if form.errors %}
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <p>Your username and password didn't match. Please try again.</p>
  </div>
{% endif %}

{% if messages %}
  <div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  </div>
{% endif %}

<form method="post" action="{% url 'login' %}" id="form-base" novalidate>
{% csrf_token %}
  <div class="form-group has-feedback">
    {{ form.username }}
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    {{ form.password }}
    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
  </div>

  <div class="row">
    <div class="col-xs-8">
      <div class="checkbox icheck">
       <!--  <label>
          <input type="checkbox"> Remember Me
        </label> -->
      </div>
    </div>
    <div class="col-xs-4">
      <button type="submit" class="btn btn-primary btn-block btn-flat">Log In</button>
    </div>
  </div>
</form>

{% endblock content %}



{% block script %}

<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>

{% endblock script %}