accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.account_list, name='account_list'),
    path('create/', views.account_create, name='account_create'),
    path('<int:pk>/edit', views.account_edit, name='account_edit'),
    path('<int:pk>/delete', views.account_delete, name='account_delete'),

]

bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('book-appointment', views.appointment_set, name='appointment_set'),
    path('appointment/', views.appointment_list, name='appointment_list'),

]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    # services
    path('list/', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/edit', views.service_edit, name='service_edit'),
    path('<int:pk>/delete', views.service_delete, name='service_delete'),

    # treatment area
    path('treatment-area/list/', views.treatment_area_list, name='treatment_area_list'),
    path('treatment-area/create/', views.treatment_area_create, name='treatment_area_create'),
    path('treatment-area/<int:pk>/edit', views.treatment_area_edit, name='treatment_area_edit'),
    path('<int:pk>/delete', views.treatment_area_delete, name='treatment_area_delete'),

    # price type
    path('price-type/list/', views.price_type_list, name='price_type_list'),
    path('price-type/create/', views.price_type_create, name='price_type_create'),
    path('price-type/<int:pk>/edit', views.price_type_edit, name='price_type_edit'),
    path('<int:pk>/delete', views.price_type_delete, name='price_type_delete'),

    # treatment
    path('treatment/list/', views.treatment_list, name='treatment_list'),
    path('treatment/create/', views.treatment_create, name='treatment_create'),
    path('treatment/<int:pk>/edit', views.treatment_edit, name='treatment_edit'),
    path('<int:pk>/delete', views.treatment_delete, name='treatment_delete'),
]

splendor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', auth_views.LoginView.as_view(template_name='accounts/auth_login.html',
                                                authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('services/', include('services.urls')),
    path('accounts/', include('accounts.urls')),
    path('bookings/', include('bookings.urls'))

]

splendor/templates/snippets/css.html
  {% load static %}

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static "assets/components/bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static "assets/components/font-awesome/css/font-awesome.min.css" %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static "assets/components/Ionicons/css/ionicons.min.css" %}">
<!-- DataTables -->
  <link rel="stylesheet" href="{% static "assets/components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static "assets/dist/css/AdminLTE.min.css" %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static "assets/dist/css/skins/_all-skins.min.css" %}">

<link rel="stylesheet" href="{% static "assets/plugins/iCheck/square/blue.css" %}">

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static "assets/dist/css/custom.css" %}">

splendor/templates/snippets/js.html
{% load static %}

<!-- jQuery 3 -->
<script src="{% static "assets/components/jquery/dist/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "assets/components/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static "assets/components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
<!-- Morris.js charts -->
<script src="{% static "assets/components/raphael/raphael.min.js" %}"></script>
<script src="{% static "assets/components/morris.js/morris.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "assets/components/jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
<!-- jvectormap -->
<script src="{% static "assets/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}"></script>
<script src="{% static "assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "assets/components/jquery-knob/dist/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "assets/components/moment/min/moment.min.js" %}"></script>
<script src="{% static "assets/components/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
<!-- datepicker -->
<script src="{% static "assets/components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static "assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}"></script>
<!-- DataTables -->
<script src="{% static "assets/components/datatables.net/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "assets/components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
<!-- Slimscroll -->
<script src="{% static "assets/components/jquery-slimscroll/jquery.slimscroll.min.js" %}"></script>
<!-- FastClick -->
{% comment %} <script src="{% static "assets/components/fastclick/lib/fastclick.js" %}"></script> {% endcomment %}
<!-- AdminLTE App -->
<script src="{% static "assets/dist/js/adminlte.min.js" %}"></script>

<script src="{% static "assets/plugins/iCheck/icheck.min.js" %}"></script>

<!-- Custom js-->
<script src="{% static "assets/dist/js/main.js" %}"></script>

splendor/templates/snippets/navbar.html
{% load static %}
<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>SSC</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Splendor Skin Clinic</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <!-- end message -->
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-light-blue"></i> You changed your username
                        </a>
                      </li>
                    </ul><div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 3px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px;"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div></div>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->

              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-fw fa-user"></i>
                  <span class="hidden-xs">Mike Sy</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <i class="fa fa-fw fa-user"></i>
                    <p>
                      Mike Sy - Admin
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'logout' %}" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li>
            </ul>
          </div>
    </nav>
  </header>

splendor/templates/snippets/sidebar.html
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <section class="sidebar">

      <ul class="sidebar-menu" data-widget="tree">
        <li class="header" style="color:#afb0b1;">MAIN NAVIGATION</li>


        <li class="{% if request.get_full_path == '/accounts/list/' %} active {% endif %}">
          <a href="{% url 'accounts:account_list' %}">
            <i class="fa fa-fw fa-users"></i>
            <span>Accounts</span>
          </a>
        </li>

        <li class="{% if request.get_full_path == '/services/list/' %} active {% endif %}">
          <a href="{% url 'services:service_list' %}">
            <i class="fa fa-fw fa-user-md"></i>
            <span>Services</span>
          </a>
        </li>

        <li class="{% if request.get_full_path == '/services/list/' %} active {% endif %}">
          <a href="{% url 'services:treatment_list' %}">
            <i class="fa fa-heartbeat"></i>
            <span>Treatments</span>
          </a>
        </li>

        <li class="{% if request.get_full_path == '/services/list/' %} active {% endif %}">
          <a href="{% url 'services:treatment_area_list' %}">
            <i class="fa fa-hotel"></i>
            <span>Treatment Areas</span>
          </a>
        </li>

        <li class="{% if request.get_full_path == '/services/list/' %} active {% endif %}">
          <a href="{% url 'services:price_type_list' %}">
            <i class="fa fa-money"></i>
            <span>Price Types</span>
          </a>
        </li>

        <li class="{% if request.get_full_path == '/services/list/' %} active {% endif %}">
          <a href="{% url 'bookings:appointment_list' %}">
            <i class="fa fa-money"></i>
            <span>Appointments</span>
          </a>
        </li>


      </ul>
    </section>

  </aside>