accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.account_list, name='account_list'),
    path('create/', views.account_create, name='account_create'),
    path('<int:pk>/edit', views.account_edit, name='account_edit'),
    path('<int:pk>/delete', views.account_delete, name='account_delete'),

]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    # services
    path('list/', views.service_list, name='service_list'),
    path('create/', views.service_create, name='service_create'),
    path('<int:pk>/edit', views.service_edit, name='service_edit'),
    path('<int:pk>/delete', views.service_delete, name='service_delete'),

    # treatment area
    path('treatment-area/list/', views.treatment_area_list, name='treatment_area_list'),
    path('treatment-area/create/', views.treatment_area_create, name='treatment_area_create'),
    path('treatment-area/<int:pk>/edit', views.treatment_area_edit, name='treatment_area_edit'),
    path('<int:pk>/delete', views.treatment_area_delete, name='treatment_area_delete'),

    # price type
    path('price-type/list/', views.price_type_list, name='price_type_list'),
    path('price-type/create/', views.price_type_create, name='price_type_create'),
    path('price-type/<int:pk>/edit', views.price_type_edit, name='price_type_edit'),
    path('<int:pk>/delete', views.price_type_delete, name='price_type_delete'),

    # treatment
    path('treatment/list/', views.treatment_list, name='treatment_list'),
    path('treatment/create/', views.treatment_create, name='treatment_create'),
    path('treatment/<int:pk>/edit', views.treatment_edit, name='treatment_edit'),
    path('<int:pk>/delete', views.treatment_delete, name='treatment_delete'),
]

splendor/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from accounts.forms import LoginForm

urlpatterns = [
    path('admin/', auth_views.LoginView.as_view(template_name='accounts/auth_login.html',
                                                authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('services/', include('services.urls')),
    path('accounts/', include('accounts.urls')),
    path('bookings/', include('bookings.urls'))

]

services/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone


# Create your models here.
class Service(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=100, default=None)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, default='Available')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'services'


class TreatmentArea(models.Model):
    area = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, default='Available')

    def __str__(self):
        return self.area

    class Meta:
        db_table = 'treatment_areas'


class PriceType(models.Model):
    type = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, default='Available')

    def __str__(self):
        return self.type

    class Meta:
        db_table = 'price_types'


class Treatment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.DO_NOTHING)
    area = models.ForeignKey(TreatmentArea, on_delete=models.DO_NOTHING)
    type = models.ForeignKey(PriceType, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, default='Available')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'treatments'

services/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm

from .models import Service, Treatment, TreatmentArea, PriceType


class ServiceForm(ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Service name must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}))

    class Meta:
        model = Service
        fields = ['name', 'description']


class TreatmentForm(ModelForm):
    service = forms.ModelChoiceField(
        queryset=Service.objects.exclude(status='Deleted'),
        widget=forms.Select(
            attrs={
                'class': 'form-control'}))

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Treatment name must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}))

    area = forms.ModelChoiceField(
        queryset=TreatmentArea.objects.exclude(status='Deleted'),
        widget=forms.Select(
            attrs={
                'class': 'form-control'}))

    type = forms.ModelChoiceField(
        queryset=PriceType.objects.exclude(status='Deleted'),
        widget=forms.Select(
            attrs={
                'class': 'form-control'}))

    price = forms.DecimalField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        error_messages={
            'required': 'Price must be a number'
        }
    )

    class Meta:
        model = Treatment
        fields = [
            'service',
            'name',
            'description',
            'area',
            'type',
            'price',
        ]


class AreaForm(ModelForm):
    area = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Treatment area must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    class Meta:
        model = TreatmentArea
        fields = ['area']


class TypeForm(ModelForm):
    type = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'}),
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\s]*$',
                message='Price type must be letters only'),
        ],
        error_messages={
            'required': ''
        }
    )

    class Meta:
        model = PriceType
        fields = ['type']

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import ServiceForm, TreatmentForm, AreaForm, TypeForm
from .models import Service, Treatment, TreatmentArea, PriceType
from django.contrib import messages


# Create your views here.
def service_list(request):
    service_list = Service.objects.exclude(status='Deleted')
    template_name = 'services/service_list.html'
    context = {'service_list': service_list}
    return render(request, template_name, context)


def service_create(request):
    form = ServiceForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service created successfully.')
        return redirect('services:service_list')
    template_name = 'services/service_create.html'
    context = {'form': form}
    return render(request, template_name, context)


def service_edit(request, pk):
    service = get_object_or_404(Service, id=pk)
    form = ServiceForm(request.POST or None, instance=service)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Service updated successfully.')
        return redirect('services:service_list')
    template_name = 'services/service_edit.html'
    context = {'service': service, 'form': form}
    return render(request, template_name, context)


def service_delete(request, pk):
    service = get_object_or_404(Service, id=pk)
    service.status = 'Deleted'
    service.save()
    messages.success(request,
                     'Service has been marked as "Deleted".')
    return redirect('services:service_list')


def treatment_area_list(request):
    treatment_area_list = TreatmentArea.objects.exclude(status='Deleted')
    template_name = 'services/treatedarea_list.html'
    context = {'area_list': treatment_area_list}
    return render(request, template_name, context)


def treatment_area_create(request):
    form = AreaForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment area created successfully.')
        return redirect('services:treatment_area_list')
    template_name = 'services/treatedarea_create.html'
    context = {'form': form}
    return render(request, template_name, context)


def treatment_area_edit(request, pk):
    treatment_area = get_object_or_404(TreatmentArea, id=pk)
    form = AreaForm(request.POST or None, instance=treatment_area)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment area updated successfully.')
        return redirect('services:treatment_area_list')
    template_name = 'services/treatedarea_edit.html'
    context = {'area': treatment_area, 'form': form}
    return render(request, template_name, context)


def treatment_area_delete(request, pk):
    treatment_area = get_object_or_404(TreatmentArea, id=pk)
    treatment_area.status = 'Deleted'
    treatment_area.save()
    messages.success(request,
                     'Treatment area has been marked as deleted.')
    return redirect('services:treatment_area_list')


def price_type_list(request):
    pricing_type_list = PriceType.objects.exclude(status='Deleted')
    template_name = 'services/pricetype_list.html'
    context = {'ptype_list': pricing_type_list}
    return render(request, template_name, context)


def price_type_create(request):
    form = TypeForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Price type created successfully.')
        return redirect('services:price_type_list')
    template_name = 'services/pricetype_create.html'
    context = {'form': form}
    return render(request, template_name, context)


def price_type_edit(request, pk):
    price_type = get_object_or_404(PriceType, id=pk)
    form = TypeForm(request.POST or None, instance=price_type)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Price type updated successfully.')
        return redirect('services:price_type_list')
    template_name = 'services/pricetype_edit.html'
    context = {'price_type': price_type, 'form': form}
    return render(request, template_name, context)


def price_type_delete(request, pk):
    price_type = get_object_or_404(PriceType, id=pk)
    price_type.status = 'Deleted'
    price_type.save()
    messages.success(request,
                     'Price type has been marked as deleted.')
    return redirect('services:price_type_list')
    template_name = 'services/pricetype_list.html'
    context = {'price_type': price_type}
    return render(request, template_name, context)


def treatment_list(request):
    treatment_list = Treatment.objects.exclude(status='Deleted')
    template_name = 'services/treatment_list.html'
    context = {'treatment_list': treatment_list}
    return render(request, template_name, context)


def treatment_create(request):
    form = TreatmentForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('services:treatment_list')
    template_name = 'services/treatment_create.html'
    context = {'form': form}
    return render(request, template_name, context)


def treatment_edit(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    form = TreatmentForm(request.POST or None, instance=treatment)
    if form.is_valid():
        form.save()
        messages.success(request,
                         'Treatment created successfully.')
        return redirect('services:treatment_list')
    template_name = 'services/treatment_edit.html'
    context = {'form': form, 'treatment': treatment}
    return render(request, template_name, context)


def treatment_delete(request, pk):
    treatment = get_object_or_404(Treatment, id=pk)
    treatment.status = 'Deleted'
    treatment.save()
    messages.success(request,
                     'Treatment has been marked as deleted.')
    return redirect('services:treatment_list')

services/templates/services/pricetype_create.html
{% extends 'base.html' %}

{% block page_title %}
    Pricing Type
{% endblock %}

{% block content %}
  <section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Price Type</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group">
          <label for="" class="col-md-2 control-label">Price Type:</label>
          <div class="col-md-4">
            {{ form.type }}
            <span class="help-block">{{ form.type.errors }}</span>
          </div>
        </div>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>
  </div>
</section>
{% endblock %}

services/templates/services/pricetype_edit.html
{% extends 'base.html' %}

{% block title %}
    Pricing Type
{% endblock %}

{% block content %}
    <h1> Add Pricing Type </h1>
    <form method="POST">
        {% csrf_token %}
         <div class="form-group">
			<label>Pricing Type:</label>
			{{form.type}}
            {{form.type.errors}}
		</div>

         <button type="submit" class="btn btn-md btn-info">Update</button>
    </form>
{% endblock %}

services/templates/services/pricetype_list.html
{% extends 'base.html' %}

{% block title %}
    Price Type List
{% endblock %}

{% block content %}
    <h5><a href="{% url 'services:price_type_create' %}">Add Price Type</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Price Type</th>
				</tr>
			</thead>

			<tbody>
				{% for type in ptype_list %}
					<tr>
						<td>{{ type.id }}</td>
						<td>{{ type.type }}</td>
						<td><a href="{% url 'services:price_type_edit' type.id %}" class="btn btn-md btn-info">
							Edit</a>
							<a href="{% url 'services:price_type_delete' type.id %}" class="btn btn-md btn-danger">
							Delete</a>
						</td>
					</tr>
				{% endfor %}

			</tbody>
		</table>
	</div>

{% endblock %}

services/templates/services/service_create.html
{% extends 'base.html' %}

{% block page_title %} Services {% endblock %}

{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Service</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Service Name:</label>
          <div class="col-md-4">
            {{ form.name }}
            <span class="help-block">{{ form.name.errors }}</span>
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Description:</label>
          <div class="col-md-4">
            {{ form.description }}
            <span class="help-block"></span>
          </div>
        </div>

      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

  </div>

</section>
{% endblock %}

services/templates/services/service_edit.html
{% extends 'base.html' %}

{% block title %}
    {{ service.name }}
{% endblock %}

{% block content %}
<h1>{{service.name}}</h1>
    <form method="POST" action="{% url 'services:service_edit' service.id %}">
        {% csrf_token %}

        <div class="form-group">
			<label>Service Name:</label>
			{{form.name}}
            {{form.name.errors}}
		</div>

        <div class="form-group">
			<label>Description:</label>
			{{form.description}}
		</div>

        <button type="submit" class="btn btn-info mt-2">Update</button>

    </form>

{% endblock %}

services/templates/services/service_list.html
{% extends 'base.html' %}

{% block title %}
    Services List
{% endblock %}

{% block content %}

	<h5><a href="{% url 'services:service_create' %}">Add Service</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Services</th>
					<th>Description</th>
					<th>Actions</th>
				</tr>
			</thead>

			<tbody>
				{% for service in service_list %}
					<tr>
						<td>{{ service.id }}</td>
						<td>{{ service.name }}</td>
						<td>{{ service.description }}</td>
						<td><a href="{% url 'services:service_edit' service.id %}" class="btn btn-md btn-info">
							Edit</a>
							<a href="{% url 'services:service_delete' service.id %}" class="btn btn-md btn-danger">
							Delete</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}

services/templates/services/treatedarea_create.html
{% extends 'base.html' %}

{% block page_title %}
    Treatment Body Area
{% endblock %}

{% block content %}
<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Treatment Body Area</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group">
          <label for="" class="col-md-2 control-label">Body Area:</label>
          <div class="col-md-4">
            {{ form.area }}
            <span class="help-block">{{ form.area.errors }}</span>
          </div>
        </div>
      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>
  </div>
</section>
{% endblock %}

services/templates/services/treatedarea_edit.html
{% extends 'base.html' %}

{% block title %}
    Treatment Area
{% endblock %}

{% block content %}
    <h1> Add Treatment Area</h1>
    <form method="POST">
        {% csrf_token %}
         <div class="form-group">
			<label>Treatment Area:</label>
			{{form.area}}
            {{form.area.errors}}
		</div>

      <button type="submit" class="btn btn-md btn-info">Update</button>

    </form>
{% endblock %}

services/templates/services/treatedarea_list.html
{% extends 'base.html' %}

{% block title %}
    Treatment Area List
{% endblock %}

{% block content %}
    <h5><a href="{% url 'services:treatment_area_create' %}">Add Treatment Area</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Treatment Area</th>
				</tr>
			</thead>

			<tbody>
				{% for area in area_list %}
					<tr>
						<td>{{ area.id }}</td>
						<td>{{ area.area }}</td>
						<td><a href="{% url 'services:treatment_area_edit' area.id %}" class="btn btn-md btn-info">
							Edit</a>
							<a href="{% url 'services:treatment_area_delete' area.id %}" class="btn btn-md btn-danger">
							Delete</a>
						</td>
					</tr>
				{% endfor %}

			</tbody>
		</table>
	</div>

{% endblock %}

services/templates/services/treatment_create.html
{% extends 'base.html' %}

{% block page_title %}
    Treatment
{% endblock %}

{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Treatment</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Service Name:</label>
          <div class="col-md-4">
            {{ form.service }}
            <span class="help-block">{{ form.service.errors }}</span>
          </div>
        </div>

		<div class="form-group">
          <label for="" class="col-md-2 control-label">Treatment Name:</label>
          <div class="col-md-4">
            {{ form.name }}
            <span class="help-block">{{ form.name.errors }}</span>
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Description:</label>
          <div class="col-md-4">
            {{ form.description }}
            <span class="help-block"></span>
          </div>
        </div>

		<div class="form-group">
          <label for="" class="col-md-2 control-label">Body Area:</label>
          <div class="col-md-4">
            {{ form.area }}
            <span class="help-block"></span>
          </div>
        </div>

		<div class="form-group">
          <label for="" class="col-md-2 control-label">Pricing Type:</label>
          <div class="col-md-4">
            {{ form.type }}
            <span class="help-block"></span>
          </div>
        </div>

	 	<div class="form-group">
          <label for="" class="col-md-2 control-label">Price:</label>
          <div class="col-md-4">
            {{ form.price }}
            <span class="help-block">{{ form.price.errors }}</span>
          </div>
        </div>

      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

services/templates/services/treatment_edit.html
{% extends 'base.html' %}

{% block title %}
    {{service.name}}
{% endblock %}

{% block content %}
<h1>{{ service.name }} {{ treatment.name }}</h1>
    <form method="POST" action="{% url 'services:treatment_edit' treatment.id %}">
        {% csrf_token %}

        <div class="form-group">
			<label>Service Name:</label>
			{{form.service}}
		</div>

        <div class="form-group">
			<label>Treatment Name:</label>
			{{form.name}}
			{{form.name.errors}}
		</div>

		<div class="form-group">
			<label>Description:</label>
			{{form.description}}
		</div>

        <div class="form-group">
			<label>Treatment Area:</label>
			{{form.area}}
		</div>

        <div class="form-group">
			<label>Pricing Type:</label>
			{{form.type}}
		</div>

         <div class="form-group">
			<label>Price:</label>
			{{form.price}}
			{{form.price.errors}}
		</div>

        <button type="submit" class="btn btn-info mt-2">Update</button>

    </form>

{% endblock %}

services/templates/services/treatment_list.html
{% extends 'base.html' %}

{% block title %}
    Treatment List
{% endblock %}

{% block content %}
	<h5><a href="{% url 'services:treatment_create' %}">Add Treatment</a></h5>

	{% if messages %}
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}

	<div class="table responsive">
		<table class="table table-bordered table-striped table-hover">
			 <thead class="thead-dark">
				<tr>
					<th>ID</th>
					<th>Services</th>
					<th>Treatments</th>
                    <th>Description</th>
					<th>Treatment Area</th>
					<th>Pricing Type</th>
					<th>Price</th>
				</tr>
			</thead>

			<tbody>
				{% for treatment in treatment_list %}
					<tr>
						<td>{{ treatment.id }}</td>
						<td>{{ treatment.service }}</td>
						<td>{{ treatment.name }}</td>
						<td>{{ treatment.description }}</td>
						<td>{{ treatment.area }}</td>
						<td>{{ treatment.type }}</td>
						<td>{{ treatment.price }}</td>
						<td><a href="{% url 'services:treatment_edit' treatment.id %}" class="btn btn-md btn-info">
							Edit</a>
							<a href="{% url 'services:treatment_delete' treatment.id %}" class="btn btn-md btn-danger">
							Delete</a>
						</td>

					</tr>
				{% endfor %}

			</tbody>
		</table>
	</div>

{% endblock %}